from pprint import pprint

malumot = {"osiyo mamlakatlari": {
    "Uzbekistan": {
        "Davlat kodi": {"uz"},
        "Davlat pul birligi": {"So'm"},
        "Davlat tili": ["O'zbek tili", "Qoraqalpoq tili"],
        "Millatlar": {"Uzbek": 84.4,
                      "Tajiks": 4.9,
                      "Kazakhs": 2.4,
                      "Karakalpaks": 2.2,
                      "Russians": 2.1,
                      "Others": 4.1,
                      },
        "Vaqt joylashuvi": "UTC+5 ",
        "Aloqa ko'di": "+998",
        "Milliy Domen": ".uz",
        "Website": "https://www.gov.uz/",
        "Avtanom Republic": "Karakalpakstan",
        "Yer maydoni": {"Umumiy": "448.9 kmkv",
                        "Toshkent": 15.258,
                        "Namangan": 7.181,
                        "Andijon": 4.303,
                        "Farg'ona": 7.005,
                        "QashqaDaryo": 28.568,
                        "Sirdaryo": 4.276,
                        "Samarqand": 16.773,
                        "Surxondaryo": 20.099,
                        "Xorazm": 6.464,
                        "Buxoro": 41.937,
                        "Navoiy": 109.375,
                        "Jizzax": 21.179,
                        "Karakalpakstan": 161.358,
                        },
        "Viloyatlari": ["Andijan", "Buxoro", "Surxondaryo", "Xorazm", "Navoiy", "Jizzax", "Fag'ona", "Namangan"],
        "Aholisi": {"Umumiy": 35300000,
                    "Toshkent": 2424100,
                    "Namangan": 2652400,
                    "Andijon": 2965500,
                    "Farg'ona": 3564800,
                    "QashqaDaryo": 3088800,
                    "Sirdaryo": 803100,
                    "Samarqand": 3651700,
                    "Surxondaryo": 2462300,
                    "Xorazm": 1776700,
                    "Buxoro": 1843500,
                    "Navoiy": 942800,
                    "Jizzax": 1301000,
                    "Karakalpakstan": 1817500,
                    },
    },
    "Kirgizistan": {
        "Davlat kodi": "KG",
        "Davlat pul birligi": {"Som"},
        "Davlat tili": ["Kyrgyz tili", "Russian tili"],
        "Millatlar": {"Kyrgyz": 73.8,
                      "Uzbek": 14.8,
                      "Dungan": 1.1,
                      "Tajiks": 4.9,
                      "Kazakhs": 2.4,
                      "Uyghur": 0.9,
                      "Russians": 5.1,
                      "Others": 4.1,
                      },
        "Vaqt joylashuvi": "UTC+5 ",
        "Aloqa ko'di": "+998",
        "Milliy Domen": ".uz",
        "Website": "https://www.gov.uz/",
        "Avtanom Republic": "Karakalpakstan",
        "Yer maydoni": {"Umumiy": "448.9 kmkv",
                        "Toshkent": 15.258,
                        "Namangan": 7.181,
                        "Andijon": 4.303,
                        "Farg'ona": 7.005,
                        "QashqaDaryo": 28.568,
                        "Sirdaryo": 4.276,
                        "Samarqand": 16.773,
                        "Surxondaryo": 20.099,
                        "Xorazm": 6.464,
                        "Buxoro": 41.937,
                        "Navoiy": 109.375,
                        "Jizzax": 21.179,
                        "Karakalpakstan": 161.358,
                        },
        "Viloyatlari": ["Andijan", "Buxoro", "Surxondaryo", "Xorazm", "Navoiy", "Jizzax", "Fag'ona", "Namangan"],
        "Aholisi": {"Umumiy": 35300000,
                    "Toshkent": 2424100,
                    "Namangan": 2652400,
                    "Andijon": 2965500,
                    "Farg'ona": 3564800,
                    "QashqaDaryo": 3088800,
                    "Sirdaryo": 803100,
                    "Samarqand": 3651700,
                    "Surxondaryo": 2462300,
                    "Xorazm": 1776700,
                    "Buxoro": 1843500,
                    "Navoiy": 942800,
                    "Jizzax": 1301000,
                    "Karakalpakstan": 1817500,
                    },
    },
    "Kazagistan": {
        "Davlat kodi": "KAZ",
        "Davlat pul birligi": "KZT",
        "Davlat tili": ["Qozoqcha", "Ruscha"],
        "Millatlar": {"Qozoqlar": 12264253,
                      "Ruslar": 3126722,
                      "Oʻzbeklar": 493783,
                      "Ukrainlar": 313698,
                      "Uygʻurlar": 237582,
                      "Tatarlar": 203371,
                      "Nemislar": 180832,
                      "Koreyslar": 103456,
                      "Turklar": 101416,
                      "Ozarbayjonlar": 9490,
                      "Beloruslar": 62694,
                      "Dunganlar": 57819,
                      "Kurdlar": 40626,
                      "Tojiklar": 39612,
                      "Polyaklar": 33301,
                      "Chechenlar": 31809,
                      "Qirgʻizlar": 23274,
                      "Boshqirdlar": 17073,
                      "Ingushlar": 15120,
                      "Moldavanlar": 14245,
                      "Yunonlar": 8846,
                      "Boshqa millatlar": 1350,

                      },
        "Vaqt joylashuvi": "UTC+5, +6",
        "Aloqa ko'di": "7",
        "Internet domeni": "kz",

        "Yer maydoni": {"Umumiy": {"2724902"},
                        "Olmota viloyati": {223911},
                        "Oqmoʻla viloyati": {146219},
                        "Aqtoʻbe viloyati": {300629},
                        "Atirau viloyati": {118631},
                        "Sharqiy Qozogʻiston Viloyati": {283226},
                        "Jambul viloyati": {144264},
                        "Gʻarbiy Qozogʻiston viloyati": {151339},
                        "Qaragʻandi viloyati": {427982},
                        "Qoʻstanay viloyati": {196001},
                        "Qiziloʻrda viloyati": {226019},
                        "Mangʻistau viloyati": {165642},
                        "Pavlodar viloyati": {124755},
                        "Ulitau viloyati": {188936, 61},
                        "Shimoliy Qozogʻiston viloyati": {97993},
                        "Turkiston viloyati": {1983967},
                        },

        "Viloyatlari": ["Olmota viloyati",
                        "Oqmoʻla viloyati",
                        "Aqtoʻbe viloyati",
                        "Atirau viloyati",
                        "Sharqiy Qozogʻiston Viloyati",
                        "Jambul viloyati",
                        "Gʻarbiy Qozogʻiston viloyati",
                        "Qaragʻandi viloyati",
                        "Qoʻstanay viloyati",
                        "Qiziloʻrda viloyati",
                        "Mangʻistau viloyati",
                        "Pavlodar viloyati",
                        "Ulitau viloyati",
                        "Shimoliy Qozogʻiston viloyati",
                        "Turkiston viloyati"],

        "Aholisi": {"Umumiy": 18157078,
                    "Olmota viloyati": 1955849,
                    "Oqmoʻla viloyati": 733175,
                    "Aqtoʻbe viloyati": 798307,
                    "Atirau viloyati": 558252,
                    "Sharqiy Qozogʻiston Viloyati": 1393792,
                    "Jambul viloyati": 1073444,
                    "Gʻarbiy Qozogʻiston viloyati": 618846,
                    "Qaragʻandi viloyati": 1364096,
                    "Qoʻstanay viloyati": 880429,
                    "Qiziloʻrda viloyati": 730256,
                    "Mangʻistau viloyati": 572226,
                    "Pavlodar viloyati": 749978,
                    "Ulitau viloyati": 226978,
                    "Shimoliy Qozogʻiston viloyati": 578856,
                    "Turkiston viloyati": 1983967,
                    }
    },
    # "Turkmenistan": {
    #     "Davlat kodi": "TM",
    #     "Davlat pul birligi": "Manat",
    #     "Davlat tili": "Turkman",
    #     "Millatlar": {
    #         "85.6% Turkmanlar",
    #         "5.8% O'zbeklar",
    #         "5.1% Ruslar",
    #         "0.4% Qozoqlar",
    #         "1.2% Ozarbayjonlar",
    #         "3.1% Others"},
    #     "Vaqt joylashuvi": "UTC +5 (TMT)",
    #     "Aloqa ko'di": "+993",
    #     "ISO 3166 code": "TM",
    #     "Internet TLD": ".tm",
    # },

    "Yer maydoni": {"Umumiy": {"491,210 kmkv"},
                    "Axal": {95.4},
                    "Bolqon": {466.877},
                    "Dashoguz": {73.430},
                    "Lebap": {93.8},
                    "Mari": {86.8},
                    },

    "Viloyatlari": ["Axal", "Bolqon", "Dashoguz", "Lebap", "Mari"],

    "Aholisi": {"Umumiy": {6, 031.187},
                "Axal": {939.700},
                "Bolqon": {553.500},
                "Dashoguz": {1, 370.400},
                "Lebap": {1, 421.100},
                "Mari": {1, 480.400},
                },
    "Afganistan": {
        "Davlat kodi": "AFG",
        "Davlat pul birligi": "AFN",
        "Davlat tili": ["O'zbek tili", "dari", "pushtu"],
        "Millatlar": {

            "Vaqt joylashuvi": "UTC +6",
            "Aloqa ko'di": "+93",
            "ISO 3166 code": "AF",
            "Internet TLD": ".AF",
        },

        "Yer maydoni": {"Umumiy": {"645 807 kmkv"},
                        "badaxshon": {44059},
                        "badg'is": {20591},
                        "bog'lon": {21118},
                        "bax": {17249},
                        "bomion": {14175},
                        "daykundi": {8088},
                        "farax": {48471},
                        "fayrob": {25124},
                        "gur": {36655},
                        "helmard": {54156},
                        "hirod": {22564},
                        "juzdon": {64125},
                        "kapisa": {545669},
                        "kabul": {54816},
                        "kunar": {32115},
                        "lag'mon": {54845},
                        "lugar": {45215},
                        "nangorhor": {15151},
                        "paktika": {1553},
                        "paktiya": {4556},
                        "panjsher": {15541},
                        "parvon": {61515},
                        "qandarhon": {21514},
                        "qunduz": {6558},
                        "samangan": {1518},
                        "saripul": {515},
                        "tohar": {12333},
                        "vardok": {8938},
                        "xost": {4142},
                        "zobul": {17343},
                        "o'rg'uzgon": {22696},
                        "g'azni": {22915},
                        },

        "Viloyatlari": ["badaxshon",
                        "badg'is",
                        "bog'lon",
                        "bax",
                        "bomion",
                        "daykundi",
                        "farax",
                        "fayrob",
                        "gur",
                        "helmard",
                        "hirod",
                        "juzdon",
                        "kapisa",
                        "kabul",
                        "kunar",
                        "lag'mon",
                        "lugar",
                        "nangorhor",
                        "paktika",
                        "paktiya",
                        "panjsher",
                        "parvon",
                        "qandarhon",
                        "qunduz",
                        "samangan",
                        "saripul",
                        "tohar",
                        "vardok",
                        "xost",
                        "zobul",
                        "o'rg'uzgon",
                        "g'azni"],

        "Aholisi": {"Umumiy": {651, 745, 27, 651, 745},
                    "badaxshon": {966789},
                    "badg'is": {504185},
                    "bog'lon": {926969},
                    "bax": {1353656},
                    "bomion": {454653},
                    "daykundi": {468178},
                    "farax": {515973},
                    "fayrob": {1013535},
                    "gur": {701653},
                    "helmard": {942093},
                    "hirod": {1928979},
                    "juzdon": {549900},
                    "kapisa": {448130},
                    "kabul": {2422},
                    "kunar": {424324},
                    "lag'mon": {4242},
                    "lugar": {24346},
                    "nangorhor": {4454},
                    "paktika": {45442},
                    "paktiya": {5463}, }
    },
    "Yevropa Davlatlari": {},
    "Afrika Davlatlari": {},
    "Janubiy Amerika Davlatlari": {},
    "Shimoliy Amerika Davlatlari": {},
    "Avstralia Davlatlari": {},
}}

pprint(malumot["osiyo mamlakatlari"])
